# Task 1

In [2]:
import pandas as pd
import numpy as np

In [3]:
df = pd.read_csv('terrorism.csv')
df = df[['country_txt', 'region_txt', 'latitude', 'longitude']]
df.shape

(2997, 4)

In [4]:
df.dropna(axis=0)

        country_txt     region_txt   latitude   longitude
0     United States  North America  44.405705  -85.714454
1          Colombia  South America   4.667128  -74.106056
2          Colombia  South America   7.198606  -75.341218
3     United States  North America  38.232471 -122.644448
4     United States  North America  39.103175  -84.511981
...             ...            ...        ...         ...
2992         Mexico  North America  17.949243  -94.916882
2993       Colombia  South America   7.745807  -76.556143
2994  United States  North America  40.262772  -76.881107
2995  United States  North America  40.261864  -76.880913
2996       Colombia  South America   1.916008  -75.242891

[2997 rows x 4 columns]

In [5]:
site = df.sample(12, random_state=8)
site = site.rename(columns = {'country_txt':'country', 'region_txt': 'region'})
site = site.reset_index(drop=True)

In [6]:
site["site_name"] = "Site " + (site.index + 1).astype(str)
site

          country         region   latitude   longitude site_name
0       Venezuela  South America   7.532824  -71.999407    Site 1
1        Colombia  South America   1.807981  -78.768396    Site 2
2   United States  North America  35.084180 -106.648639    Site 3
3        Colombia  South America   1.641284  -77.734463    Site 4
4        Colombia  South America   7.301376  -72.492754    Site 5
5        Colombia  South America   6.963234  -71.881599    Site 6
6   United States  North America  40.697132  -73.931351    Site 7
7          Mexico  North America  27.480024  -99.510535    Site 8
8        Colombia  South America   2.519314  -74.753891    Site 9
9   United States  North America  38.853889  -94.781111   Site 10
10  United States  North America  29.984368  -90.257301   Site 11
11  United States  North America  26.071231  -80.145668   Site 12

# Task 2

In [5]:
import matplotlib.pyplot as plt

In [7]:
plt.scatter(site['longitude'], site['latitude'])
plt.title('Points')
plt.xlabel('Longitude')
plt.ylabel('Latitude')

Text(0, 0.5, 'Latitude')

:

It's missing a map to show where these points actually are in space

# Task 3

In [6]:
import folium

In [9]:
map = folium.Map([10, -70], zoom_start=3)
map

In [10]:
for index, row in site.iterrows():
    folium.Marker([row['latitude'], row['longitude']], popup=row['site_name'], tooltip=row['country']).add_to(map)
map

# Task 4

In [7]:
import geopandas as gpd

In [16]:
points = gpd.points_from_xy(site['longitude'], site['latitude'])
site_gdf = gpd.GeoDataFrame(site, geometry=points)
site_gdf

,country,region,latitude,longitude,site_name,geometry
0,Venezuela,South America,7.532824,-71.999407,Site 1,POINT (-71.99941 7.53282)
1,Colombia,South America,1.807981,-78.768396,Site 2,POINT (-78.7684 1.80798)
2,United States,North America,35.084180,-106.648639,Site 3,POINT (-106.64864 35.08418)
3,Colombia,South America,1.641284,-77.734463,Site 4,POINT (-77.73446 1.64128)
4,Colombia,South America,7.301376,-72.492754,Site 5,POINT (-72.49275 7.30138)
5,Colombia,South America,6.963234,-71.881599,Site 6,POINT (-71.8816 6.96323)
6,United States,North America,40.697132,-73.931351,Site 7,POINT (-73.93135 40.69713)
7,Mexico,North America,27.480024,-99.510535,Site 8,POINT (-99.51054 27.48002)
8,Colombia,South America,2.519314,-74.753891,Site 9,POINT (-74.75389 2.51931)
9,United States,North America,38.853889,-94.781111,Site 10,POINT (-94.78111 38.85389)
10,United States,North America,29.984368,-90.257301,Site 11,POINT (-90.2573 29.98437)
11,United States,North America,26.071231,-80.145668,Site 12,POINT (-80.14567 26.07123)

In [17]:
ven_point = site_gdf.iloc[0]['geometry']
ven_buffer = ven_point.buffer(2)
folium.Circle(location=[10.4828, -66.9621], radius=1000, color='blue', fill=True).add_to(map)
map

In [18]:
chmap = folium.Map([10, -70], zoom_start=3)
chmap

## Task 5

In [19]:
na_gdf = site_gdf[site_gdf['region']=='North America']
na_gdf

,country,region,latitude,longitude,site_name,geometry
2,United States,North America,35.084180,-106.648639,Site 3,POINT (-106.64864 35.08418)
6,United States,North America,40.697132,-73.931351,Site 7,POINT (-73.93135 40.69713)
7,Mexico,North America,27.480024,-99.510535,Site 8,POINT (-99.51054 27.48002)
9,United States,North America,38.853889,-94.781111,Site 10,POINT (-94.78111 38.85389)
10,United States,North America,29.984368,-90.257301,Site 11,POINT (-90.2573 29.98437)
11,United States,North America,26.071231,-80.145668,Site 12,POINT (-80.14567 26.07123)

In [20]:
na_points = na_gdf.unary_union
na_hull = na_points.convex_hull
folium.GeoJson(na_hull).add_to(chmap)
chmap

C:\Users\Kura\AppData\Local\Temp\ipykernel_21888\4144390532.py:1: DeprecationWarning: The 'unary_union' attribute is deprecated, use the 'union_all()' method instead.
  na_points = na_gdf.unary_union

In [21]:
sa_gdf = site_gdf[site_gdf['region']=='South America']

sa_gdf

,country,region,latitude,longitude,site_name,geometry
0,Venezuela,South America,7.532824,-71.999407,Site 1,POINT (-71.99941 7.53282)
1,Colombia,South America,1.807981,-78.768396,Site 2,POINT (-78.7684 1.80798)
3,Colombia,South America,1.641284,-77.734463,Site 4,POINT (-77.73446 1.64128)
4,Colombia,South America,7.301376,-72.492754,Site 5,POINT (-72.49275 7.30138)
5,Colombia,South America,6.963234,-71.881599,Site 6,POINT (-71.8816 6.96323)
8,Colombia,South America,2.519314,-74.753891,Site 9,POINT (-74.75389 2.51931)

In [22]:
sa_points = sa_gdf.unary_union
sa_hull = sa_points.convex_hull
folium.GeoJson(sa_hull).add_to(chmap)
chmap

C:\Users\Kura\AppData\Local\Temp\ipykernel_21888\4097500579.py:1: DeprecationWarning: The 'unary_union' attribute is deprecated, use the 'union_all()' method instead.
  sa_points = sa_gdf.unary_union

A convex hull is taking every point you give it, then making a polygon out of the points that contain every point.

## Task 6

In [28]:
na_wkt = "POLYGON((-106 35, -99 27, -73 40, -94 38, -106 35))"

na_polygon = gpd.GeoSeries.from_wkt([na_wkt])

na_polygon = na_polygon.set_crs("EPSG:4326")

na_map = folium.Map(location=[32, -80], zoom_start=5)
folium.GeoJson(na_polygon).add_to(na_map)

na_map

In [32]:
broken_wkt = "POLYGON((-106 35, -99 27, -94 38, -73 40, -106 35))"

broken_polygon = gpd.GeoSeries.from_wkt([broken_wkt])

broken_polygon = broken_polygon.set_crs("EPSG:4326")

broken_map = folium.Map(location=[32, -80], zoom_start=5)
folium.GeoJson(broken_polygon).add_to(broken_map)

broken_map

# The order of the points matters when building a shape by hand because the shape is built in the order of the points,
# Giving the wrong order makes the shape cross over itself

## Task 7

In [34]:
boundary_lat = 15

north_wkt = f"POLYGON((-180 {boundary_lat}, -30 {boundary_lat}, -30 90, -180 {boundary_lat}))"
south_wkt = f"POLYGON((-180 -60, -30 -60, -30 {boundary_lat}, -180 {boundary_lat}, -180 -60))"

north_zone = gpd.GeoSeries.from_wkt([north_wkt])
south_zone = gpd.GeoSeries.from_wkt([south_wkt])

zones_gdf = gpd.GeoDataFrame({
    "zone_name": ["North America", "South America"],
    "geometry": [north_zone[0], south_zone[0]]
})

zones_gdf

       zone_name                                           geometry
0  North America       POLYGON ((-180 15, -30 15, -30 90, -180 15))
1  South America  POLYGON ((-180 -60, -30 -60, -30 15, -180 15, ...

In [38]:
north_polygon = gpd.GeoSeries.from_wkt([north_wkt], crs="EPSG:4326")
south_polygon = gpd.GeoSeries.from_wkt([south_wkt], crs="EPSG:4326")

ns_map = folium.Map(location=[32, -80], zoom_start=8)
folium.GeoJson(north_polygon).add_to(ns_map)
folium.GeoJson(south_polygon).add_to(ns_map)

ns_map

## Task 8

In [39]:
points = gpd.points_from_xy(
    site['longitude'], site['latitude']
)

points_gdf = gpd.GeoDataFrame(site, geometry=points)

joined_gdf = gpd.sjoin(points_gdf, zones_gdf)

joined_gdf

,country,region,latitude,longitude,site_name,geometry,index_right,zone_name
0,Venezuela,South America,7.532824,-71.999407,Site 1,POINT (-71.99941 7.53282),1,South America
1,Colombia,South America,1.807981,-78.768396,Site 2,POINT (-78.7684 1.80798),1,South America
2,United States,North America,35.084180,-106.648639,Site 3,POINT (-106.64864 35.08418),0,North America
3,Colombia,South America,1.641284,-77.734463,Site 4,POINT (-77.73446 1.64128),1,South America
4,Colombia,South America,7.301376,-72.492754,Site 5,POINT (-72.49275 7.30138),1,South America
5,Colombia,South America,6.963234,-71.881599,Site 6,POINT (-71.8816 6.96323),1,South America
6,United States,North America,40.697132,-73.931351,Site 7,POINT (-73.93135 40.69713),0,North America
7,Mexico,North America,27.480024,-99.510535,Site 8,POINT (-99.51054 27.48002),0,North America
8,Colombia,South America,2.519314,-74.753891,Site 9,POINT (-74.75389 2.51931),1,South America
9,United States,North America,38.853889,-94.781111,Site 10,POINT (-94.78111 38.85389),0,North America
10,United States,North America,29.984368,-90.257301,Site 11,POINT (-90.2573 29.98437),0,North America
11,United States,North America,26.071231,-80.145668,Site 12,POINT (-80.14567 26.07123),0,North America

They all matched.

## Task 9

In [11]:
pc = df[(df['country_txt'] == 'Peru') | (df['country_txt'] == 'Chile')]

pc = pc.sample(12, random_state=8)
pc = pc.rename(columns = {'country_txt':'country', 'region_txt': 'region'})
pc = pc.reset_index(drop=True)

pc

   country         region   latitude  longitude
0    Chile  South America -33.366238 -70.505302
1     Peru  South America -11.254017 -74.637381
2     Peru  South America -15.484792 -70.125050
3    Chile  South America -33.366238 -70.505302
4    Chile  South America -33.366238 -70.505302
5    Chile  South America -33.366238 -70.505302
6     Peru  South America -11.967368 -76.978462
7    Chile  South America -33.366238 -70.505302
8    Chile  South America -33.366238 -70.505302
9    Chile  South America -33.366238 -70.505302
10   Chile  South America -33.366238 -70.505302
11    Peru  South America -12.767585 -73.656398

In [19]:
# Plot the points
plt.scatter(pc['longitude'], pc['latitude'])
plt.title('Points')
plt.xlabel('Longitude')
plt.ylabel('Latitude')

Text(0, 0.5, 'Latitude')

:

In [12]:
pc_map = folium.Map([-75, 15], zoom_start=3)

for index, row in pc.iterrows():
    folium.Marker([row['latitude'], row['longitude']], popup=row['country'], tooltip=row['country']).add_to(pc_map)

pc_map

In [8]:
# Build a Boundary Between Two Countries

boundary_lat = -16

north_wkt = f"POLYGON((-180 {boundary_lat}, -30 {boundary_lat}, -30 90, -180 {boundary_lat}))"
south_wkt = f"POLYGON((-180 -60, -30 -60, -30 {boundary_lat}, -180 {boundary_lat}, -180 -60))"

north_zone = gpd.GeoSeries.from_wkt([north_wkt])
south_zone = gpd.GeoSeries.from_wkt([south_wkt])

zones_gdf = gpd.GeoDataFrame({
    "zone_name": ["Peru", "Chile"],
    "geometry": [north_zone[0], south_zone[0]]
})

zones_gdf

  zone_name                                           geometry
0      Peru    POLYGON ((-180 -16, -30 -16, -30 90, -180 -16))
1     Chile  POLYGON ((-180 -60, -30 -60, -30 -16, -180 -16...

In [13]:
points = gpd.points_from_xy(
    pc['longitude'], pc['latitude']
)

pc_gdf = gpd.GeoDataFrame(pc, geometry=points)

joined_gdf = gpd.sjoin(pc_gdf, zones_gdf)

joined_gdf

,country,region,latitude,longitude,geometry,index_right,zone_name
0,Chile,South America,-33.366238,-70.505302,POINT (-70.5053 -33.36624),1,Chile
1,Peru,South America,-11.254017,-74.637381,POINT (-74.63738 -11.25402),0,Peru
2,Peru,South America,-15.484792,-70.125050,POINT (-70.12505 -15.48479),0,Peru
3,Chile,South America,-33.366238,-70.505302,POINT (-70.5053 -33.36624),1,Chile
4,Chile,South America,-33.366238,-70.505302,POINT (-70.5053 -33.36624),1,Chile
5,Chile,South America,-33.366238,-70.505302,POINT (-70.5053 -33.36624),1,Chile
6,Peru,South America,-11.967368,-76.978462,POINT (-76.97846 -11.96737),0,Peru
7,Chile,South America,-33.366238,-70.505302,POINT (-70.5053 -33.36624),1,Chile
8,Chile,South America,-33.366238,-70.505302,POINT (-70.5053 -33.36624),1,Chile
9,Chile,South America,-33.366238,-70.505302,POINT (-70.5053 -33.36624),1,Chile
10,Chile,South America,-33.366238,-70.505302,POINT (-70.5053 -33.36624),1,Chile
11,Peru,South America,-12.767585,-73.656398,POINT (-73.6564 -12.76758),0,Peru

## Task 10

In [14]:
pc_gdf.explore()

## Task 11

1. Buffer
2. Convex hull, they want